In [1]:
import numpy as np 
import pandas as pd 

1. Stworz 1D array liczb 0 do 9

In [41]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Stwórz 3x3 numpy array wartości True

In [40]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Wyciągnij wszystkie nieparzyste wartości z wektora arr

In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
mask = np.ones(len(arr), dtype=bool)
mask[arr[arr%2 == 1]] = False
result = arr[mask]
result

array([0, 2, 4, 6, 8])

4. Zastąp wszystkie wartości nieparzyste wektora arr warością -1

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 == 1] = -1

5. Przekształć wektor 1D na 2D zawierający 2 wiersze

In [ ]:
arr = np.arange(10).reshape(2, 5)

6. Połącz wektory a i b wertykalnie

In [39]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a, b), axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

7. Połącz wektory a i b horyzontalnie

In [38]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a, b), axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

8. Usuń z wektora a wszystkie elementy obecne w wektorze b

In [37]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

10. Uzyskaj wszystkie elementy wektora a pomiędzy wartościami 5 i 10

In [36]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a > 5) & (a < 10)]

array([6, 9])

11. Zamień kolumny 1 and 2 w array arr

In [18]:
arr = np.arange(9).reshape(3,3)
arr[:,[1, 2]] = arr[:,[2, 1]]
arr

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

12. Zamień wiersze 1 and 2 w array arr

In [20]:
arr = np.arange(9).reshape(3,3)
arr[[1,2],:] = arr[[2,1],:]
arr

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

13. Odwróć wiersze 2D array arr

In [3]:
arr = np.arange(9).reshape(3,3)
# np.fliplr()arr

14. Odwróć kolumny 2D array arr

In [6]:
arr = np.arange(9).reshape(3,3)
np.flipud(arr)

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

15. Znajdż wartość średnią, medianę i standardowe odchylenie słowa iris

In [5]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
np.mean(sepallength)
np.std(sepallength)
np.median(sepallength)

5.8

16. Stwórz znormalizowną długość słowa dokładnie w zakresie od 0 do 1

In [8]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
norm = (sepallength - np.min(sepallength)) / np.ptp(sepallength)
norm

17. Oblicz min/max dla każdego wiersza danego arraya

In [10]:
a = np.random.randint(1,10, [5,3])
np.min(a, axis=1)
np.max(a, axis=1)

array([5, 2, 2, 1, 2])

18. Znajdź duplikaty w przedstawionym numpy arryay i oznacz je jako True. Pierwsze pojawienie
powinno byc jako False

In [10]:
a = np.random.randint(0, 5, 10)
u, indicies = np.unique(a, return_index=True)
print(f'Array: {a}')
print(f'Duplicates in indicies: {indicies}')

Array: [0 0 2 2 3 0 3 0 4 4]
Duplicates in indicies: [0 2 4 8]


19. Pozbądz się wszystkich nan wartości z wektora 1D

In [3]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
np.isnan(a)
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

20. Oblicz odległość euklidesową pomiędzy wektorem a i b

In [32]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
np.linalg.norm(a-b)

6.708203932499369

21. Odejmi 1d arrat od 2d array w taki sposób zę każdy element wektora 1d jest odejmowany od
opdowiadającego elementu wiersza wektora 2d

In [13]:
a = np.array([[3,3,3],[4,4,4],[5,5,5]])
b = np.array([1,1,1])
a - b

array([[2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

22. Wymnóż dwie dane macierze (dot)

In [31]:
x = [[1, 0], [0, 1]]
y = [[1, 2], [3, 4]]
np.dot(a, b)

array([19, 31,  4])

23. Oblicz produkt zewnętrzny (outer product) macierzy x i y

In [29]:
x = [[1, 0], [0, 1]]
y = [[1, 2], [3, 4]]
np.outer(a, b)

array([[ 8, 10, 12],
       [ 4,  5,  6],
       [ 4,  5,  6],
       [ 4,  5,  6],
       [12, 15, 18],
       [ 8, 10, 12],
       [ 4,  5,  6],
       [ 0,  0,  0],
       [ 0,  0,  0]])

24. Oblicz produkt krzyżowy dwóch macierzy x i y jak i również y i x (cross product)

In [30]:
x = [[1, 0], [0, 1]]
y = [[1, 2], [3, 4]]
np.cross(x, y)
np.cross(y,x)

array([-2,  3])

25. Oblicz wyznacznik wektora 2D

In [33]:
a = np.array([[1,2,3],[4,5,6],[0,1,0]])
np.linalg.det(a)

6.0

26. Oblicz macierz odwrotną

In [34]:
a = np.array([[1,2,3],[4,5,6],[0,1,0]])
np.linalg.inv(a)

array([[-1.        ,  0.5       , -0.5       ],
       [ 0.        ,  0.        ,  1.        ],
       [ 0.66666667, -0.16666667, -0.5       ]])

27. Oblicz macierzowo równania
2a + b + c = 4
a + 3b + 2c = 5
a = 6

In [35]:
a = np.array([[2,1,1], [1,3,2], [1,0,0]])
b = np.array([4,5,6])
np.linalg.solve(a,b)

array([  6.,  15., -23.])

28. Połącz serie ser1 i ser2 tak żeby stworzyć dataframe

In [22]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'), name="letters")
ser2 = pd.Series(np.arange(26), name="numbers")
s = pd.DataFrame(ser1)
df = s.join(ser2)
df

29. Z serii ser1 usuń elementy występujące w serii 2 ser2

In [5]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
arr = ser1.drop([i for i in ser1 if i in ser2])
arr

0    1
dtype: int64

33. Zaimportuj plik csv do dataframe z linku uwzględnijąc tylko kolumny crim i medv (https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv)

In [5]:
boston = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', header=0, index_col=["crim", "medv"], usecols=["crim", "medv"])
boston